[admiral]

items = ["left", "greet", "wsfw", "wsbk", "workspaces",
         "closeclick", "closeclick", "endbar",
         "right", "modes", "volup", "voldn", "mute",
         "prim", "volume", "space",
         "closeclick", "closeclick", "closeclick",
         "sec", "todo", "calendar", "clock",
         "closeclick", "closeclick", "endbar",
         "hilite", "space", "battery", "endbar"]


[workspaces]
path = "~/.config/lemonbar/workspace"

[modes]
path = "~/.config/lemonbar/modes"

[timeicon]

path = "echo '  '"

static = true

[clock]
# path = "date '+%a %d %b %H:%M:%S'"
path = "date '+%a %d %b %H:%M'"
reload = 1

[battery]
path = "~/.config/lemonbar/battery"
reload = 10

[volume]
path = "~/.config/lemonbar/soundstate"
reload = 0.1

[greet]


path = "echo '%{B#af6a82}%{F#271e1f}    %{F-}%{B-}%{B#8a7e8f}%{F#271e1f}    fullsalvo   '%{F-}%{B-}"


static = true

[prim]
path = "echo '%{B#8a7e8f}%{F#271e1f}  '"
static = true

[sec]
path = "echo '%{B#af6a82}%{F#271e1f}  '"
static = true

[hilite]
path = "echo '%{B#70a2cb}%{F#271e1f}  '"
static = true

[endbar]
path = "echo '  %{B-}%{F-}'"
static = true

# Clickable Regions
[todo]
path = "echo '%{A:~/.bin/todo:}'"
static = true

[calendar]
path = "echo '%{A3:notify-send \"Calendar\" \"`ncal -h`\":}'"
static = true

[nowplaying]
path = "echo '%{A:~/.bin/mpc-notify:}'"
static = true

[wsbk]
path = "echo '%{A5:~/.config/lemonbar/wsbk:}'"
static = true

[wsfw]
path = "echo '%{A4:~/.config/lemonbar/wsfw:}'"
static = true

[volup]
path = "echo '%{A4:~/.config/lemonbar/volup:}'"
static = true

[voldn]
path = "echo '%{A5:~/.config/lemonbar/voldn:}'"
static = true

[mute]
path = "echo '%{A3:~/.config/lemonbar/mute:}'"
static = true

[closeclick]
path = "echo '%{A}'"
static = true

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[reset]
path = "echo '%{F-}'"
static = true

[separator]
path = "echo '  |  '"
static = true

[space]
path = "echo '  '"
static = true
