#!/bin/bash
#
# bar - lemonbar output
# (c) arcetera 2015 - wtfpl
#

# desktop() {
#   groupstat | sed -e s/0//g -e s/1/'%{F#c1c4bc}%{F-}'/g
# }

# clock() {
#   date=$(date "+%a %d %b %l:%M")
#   printf '%s\n' "%{F#c1c4bc}%{F-} $date"
# }

# battery() {
#   bat=$(cat /sys/class/power_supply/BAT0/capacity)
#   printf '%s\n' "%{F#c1c4bc}%{F-} $bat%"
# }

# win() {
#   name=$(wname $(pfw))
#   if [ -z $name ]; then
#     if [ "$(winclass c $(pfw))" = "st-256color" ]; then
# 	  name="st"
# 	else
#       name="none"
# 	fi
#   fi
#   printf '%s\n' "%{F#c1c4bc}%{F-} $name"
# }

# while :; do
#   buf=""
#   buf="${buf} $(clock)"
#   buf="${buf} %{r}$(battery)"
#   printf '%s\n' "$buf"
#   sleep 1
# done | lemonbar -B '#1f1f22' -F '#839496' -d -f "leggie:size=11" -f "fontawesome:size=11"

battery () {
    battery="$(</sys/class/power_supply/BAT0/capacity)"
    charging="$(</sys/class/power_supply/BAT0/status)"

    case "$battery" in
        [0-9]|10)
            battery="${battery}%  "
        ;;

        1[0-9]|2[0-5])
            battery="${battery}%  "
        ;;

        2[6-9]|3[0-9]|4[0-9]|50)
            battery="${battery}%  "
        ;;

        5[1-9]|6[0-9]|7[0-5])
            battery="${battery}%  "
        ;;

        7[6-9]|8[0-9]|9[0-9]|100)
            battery="${battery}%  "
        ;;
    esac

    [ "$charging" == "Charging" ] && \
        battery="Charging  $battery"

    printf "%s" "$battery"
}

workspaces() {
	cur=$(xprop -root -notype _NET_CURRENT_DESKTOP)
	cur=$(echo $cur | cut -d= -f2)
	case $cur in
		0)
			printf "  1 2 3 4 5"
			;;
	esac
}

while :; do
    echo " $(workspaces)%{c}$(date "+%a %d %b %l:%M %p")%{r}$(battery)     %{r}"
	sleep 1s
done
