#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        /lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        /home/fullsalvo/.bin/lock.sh && systemctl suspend
        ;;
    hibernate)
        /home/fullsalvo/.bin/lock.sh && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
