#!/usr/bin/env bash
# Daemon for mpc-notify.

sleep 5
last="$(mpc current)"
# Enter message loop
while mpc idle > /dev/null; do
	# Check if the song changed
	song="$(mpc current)"
	[[ "$song" != "$last" ]] && mpc-notify
	last="$song"
done
