#!/bin/bash

direc="$HOME/.config/whizkers/variable_sets/themes/3d/"

for i in ${direc}/*; do
    name=$(basename $i .yaml)
    wall=$(cat "${i}" | grep wallpaper: | sed 's/wallpaper\://; s/"//; s/"//')
    if [ ! -z $wall ]; then
		if [ "$#" -ne 0 ]; then
			for j in "$@"; do
				name+=" ${j}"
			done
		fi
		rhisk ${name}
		sleep 0.5
		# notify-send "Theme:" "${name}"
		sleep 1.5
    fi
done

rhisk "$@"
