#!/usr/bin/env python3

import i3ipc

i3 = i3ipc.Connection()

workspaces = i3.get_workspaces()
ws_nums = []

for n in workspaces:
    ws = eval(str(n))
    if ws['visible'] == True:
        focused = int(ws['num'])
    ws_nums.append(int(ws['num']))

for n in range(len(ws_nums)):
    if ws_nums[n] == focused:
        focused = n

if focused > 0:
    i3.command("workspace %s" % (str(ws_nums[focused - 1]) + ''))
