#!/usr/bin/env bash
files="$@"

if [[ -z "${files}" ]]; then
	printf 'You must submit a file to be uploaded!\n'
	exit 1
else
	printf 'Uploading file(s) now!'
	n=1
	for i in "$@"; do
		printf "\nUploading file #${n} ... "
		out=$(curl -sf -F file="@${i}" -F contentType="image" -F encrypt="true" -F savekey="true"  https://dev.teknik.io/v1/Upload?sub=api)
		if [[ "${out}" =~ "error" ]]; then
			printf 'error uploading file!\n'
			exit 1
		else
			out="${out##*Name\":\"}"
			out="${out%%\"*}"
			printf "uploaded! Your file can be found at https://dev.teknik.io/${out}?sub=upload\n"
		fi
		printf "${out}\n"
		((n++))
	done
fi
