#!/usr/bin/env bash
# Script Name: rhisk
# Written by fullsalvo
# Loads wzk templates including those from subfolders

out=""

for i in "$@"; do
    tem=$(whizkers -l | grep $i)
    if [[ ! -z tem ]]; then
	lines=$(echo "$tem" | wc -l)
	if [[ lines -eq 1 ]]; then
	    out+="${tem} "
	fi
    fi
done

wzk $out



out=""
direc="$HOME/.config/whizkers/variable_sets"
for i in "$@"; do
    if [[ -e "${direc}/${i}.yaml" ]]; then
	out+="${i} "
    else
	check=$(find $direc -name $i.yaml)
	if [[ ! -z $check ]]; then
	    check="${check##${direc}/}"
	    check="${check%%.yaml}"
	    out+="${check} "
	else
	    err "Template \'${i}\' doesn't exist. Please choose a valid template.\n"
	    exit 1
	fi
    fi
done

wzk $out
exit 0
