#!/usr/bin/env bash
# Script Name: rhisk
# Written by fullsalvo
# Loads wzk templates including those from subfolders

out=""
direc="$HOME/.config/whizkers/variable_sets"

for i in "$@"; do
    if [[ -e "${direc}/${i}.yaml" ]]; then
	out+="${i} "
    else
	check=$(find $direc -name $i.yaml)
	if [[ ! -z $check ]]; then
	    check="${check##${direc}/}"
	    check="${check%%.yaml}"
	    out+="${check} "
	fi
    fi
done

wzk $out
