#!/usr/bin/env bash
# Reload the desktop

xrdb -merge ~/.XResources &>/dev/null
tmux source-file ~/.tmux.conf &>/dev/null

# Reload colors
for pts in /dev/pts/*; do
	(echo -n "$(use-colors < ~/.XResources)" > $pts) 2>/dev/null
done

killall compton &>/dev/null
killall dunst &>/dev/null
i3-msg 'restart' &>/dev/null

compton &>/dev/null &
dunst &>/dev/null &

