#!/usr/bin/env python

"""
A simple program that makes a diamond pattern of stars (*) of size n-1
from the center. It can also print only either the left or right half
of the diamond.
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter

def parse_args():
    parser = ArgumentParser(description=__doc__,
                            formatter_class=RawDescriptionHelpFormatter)

    parser.add_argument('-l',
                        help="""
                        Only print the left side of the pattern
                        """,
                        dest='left',
                        action='store_true',
                        default=False)

    parser.add_argument('-r',
                        help="""
                        Only print the right side of the pattern
                        """,
                        dest='right',
                        action='store_true',
                        default=False)

    parser.add_argument('size',
                        nargs='?',
                        help="""
                        Set the size of the pattern
                        """,
                        type=int,
                        default=5)

    return parser.parse_args()

def left():
    for i in range(1,2*args.size):
        if i < (args.size+1):
            out = (args.size-i)*" " + i*"*"
        else:
            out = (i-args.size)*" " + (2*args.size-i)*"*"
        print out

def right():
    for i in range(1,2*args.size):
        if i < (args.size+1):
            out = (args.size-1)*" " + i*"*"
        else:
            out = (args.size-1)*" " + (2*args.size-i)*"*"
        print out

def full():
    for i in range(1,2*args.size):
        if i < (args.size+1):
            out = (args.size-i)*" " + ((2*i)-1)*"*"
        else:
            out = (i-args.size)*" " + (2*(2*args.size-i)-1)*"*"
        print out

def main():
    if args.left:
        left()
    elif args.right:
        right()
    else:
        full()

if __name__ == '__main__':
    args = parse_args()
    main()
