#!/usr/bin/env bash
# Name: todo
# Author: fullsalvo
# Uses dunstify to display a to-do list

DUNSTIFY_ID="/tmp/todo_dunstify_id"

err() {
	printf "\e[31m$1\e[0m" >&2
}

notify ()
{
	[ ! -z "$(cat "$DUNSTIFY_ID")" ] && id_arg="-r $(cat "$DUNSTIFY_ID")"

	dunstify \
		-a "todo" \
		-p $id_arg > "$DUNSTIFY_ID" \
		"To Do:" "$msg_out"
}

if [ -n "$(t)" ]; then
	msg_out=$(t)
else
	msg_out="You have nothing to do!"
fi

notify
