#!/bin/bash

while :;do
WIN=$(xdotool getactivewindow)
    if [ -n "$WIN" ]; 
    then
	feh --bg-fill $HOME/Pictures/Walls/PosedLook.jpg
    else
	hsetroot -fill $HOME/Pictures/Walls/PosedLook.jpg -blur 50
    fi
done
