#!/usr/bin/env bash
# Runs whizkers with environment variable support, asks for a theme using
# dmenu, and reloads the desktop.

yes 2>/dev/null | relink-config >/dev/null

if [ "$?" -ne 0 ]; then
  echo 'relink-config FAILED'
  exit 1
fi

if [ "$#" -eq 0 ]; then
    whizkers -e >/dev/null
#    wzwall
else
    whizkers -e "$@" >/dev/null
#    wzwall "$1"
fi

[ "$?" -ne 0 ] && exit 1

reload-desktop
[ "$#" -ne 0 ] && sleep 0.5

exit 0
