#!/usr/bin/env bash
# Associates wallpapers with whizkers themes

dir=$HOME/.config/whizkers

if [ "$#" -eq 0 ]; then
    wall=$(cat $dir/defaults.yaml | grep wallpaper: | sed 's/wallpaper\://; s/"//; s/"//')
    feh --bg-fill $wall
else
    wall=$(cat $dir/variable_sets/$1.yaml | grep wallpaper: | sed 's/wallpaper\://; s/"//; s/"//')
    if [ ! -z $wall ]; then
	feh --bg-fill --no-feh-bg $wall
    fi
fi
