#!/usr/bin/env bash

pkill admiral &>/dev/null
pkill lemonbar &>/dev/null

$HOME/.local/bin/admiral | lemonbar -u 2 -p -B "#FF353945" -F "#eeeeee" -f "Fira Mono:size=7" -o -1 -f "FontAwesome:size=8" -f "Siji-7" -f "Symbola-7" -g 1920x18+0+0 | sh
